server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.user": ""
  "browserstack.key": ""
  "project": "Ruby Cucumber iOS Project"
  "build": "Ruby-Cucumber-build-1"
  "name": "parallel_test_1"
  "browserstack.debug": true
  "browserstack.networkLogs": true
  "platformName": 'iOS'
  "app": "bs://295be5520a1498740f20858a3ad2af9426756a83"

browser_caps:
  -
    "device": "iPhone 11 Pro"
    "os_version": "13"

  -
    "device": "iPhone 11 Pro Max"
    "os_version": "13"
